word_list = [
    "camel",
    "iloveyou",
    "monu",
    "manoj",
    "baby",
    "aardvark",
    "baboon",
    "interesting",
    "manifestation",
    "sacrifice",
    "lover",
    "monika",
    "monikasidar",
]